name: Build ONNX Runtime

on: [workflow_dispatch]

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
    - name: Checkout
      run: git clone --recursive https://github.com/zqstdy/onnxruntime.git onnxruntime-src
      
    - name: Build
      run: |
        cd onnxruntime-src/cmake
        cmake -B build -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=Release -Donnxruntime_BUILD_SHARED_LIB=OFF
        cmake --build build --config Release
      shell: cmd

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: git clone --recursive https://github.com/zqstdy/onnxruntime.git onnxruntime-src
      
    - name: Build
      run: |
        cd onnxruntime-src/cmake
        cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -Donnxruntime_BUILD_SHARED_LIB=OFF
        cmake --build build
      shell: bash
